import Head from 'next/head';

export const Meta = () => {
  return (
    <>
      <Head>
        <title>タイトル</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.icon" />
      </Head>
    </>
  );
};
